[tox]
envlist =
    py310-django52
    py310-django52-tink113
    py311-django52
    py312-django52
    py312-django60
    py313-django52
    py313-django60
    py314-django52
    py314-django60

[testenv]
package = editable
extras = test
deps =
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
    tink113: tink==1.13.0
setenv =
    PYTHONWARNINGS = default
commands =
    python -m pytest
    python -m pytest -c example_project/pytest.ini example_project/example_app/tests
