# Generated by Django 4.1a1 on 2022-07-08 11:06

from django.db import migrations, models
import django.db.models.deletion
import tink_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Key",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_url", models.CharField(max_length=250)),
                ("key_data", tink_fields.fields.EncryptedBinaryField()),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[
                            ("UNKNOWN_STATUS", 0),
                            ("ENABLED", 1),
                            ("DISABLED", 2),
                            ("DESTROYED", 3),
                        ]
                    ),
                ),
                (
                    "output_prefix_type",
                    models.PositiveIntegerField(
                        choices=[
                            ("UNKNOWN_PREFIX", 0),
                            ("TINK", 1),
                            ("LEGACY", 2),
                            ("RAW", 3),
                            ("CRUNCHY", 4),
                        ]
                    ),
                ),
                ("output_prefix", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="Keyset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "primary_key",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_key",
                        to="tink_fields.key",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="key",
            name="keyset",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="tink_fields.keyset",
            ),
        ),
    ]
