# Generated by Django 3.2.13 on 2022-06-12 09:54

from django.db import migrations, models
import django.db.models.deletion
import tink_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Keyset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("type_url", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Key",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField()),
                ("key_data", tink_fields.fields.EncryptedBinaryField()),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[
                            ("UNKNOWN_STATUS", 0),
                            ("ENABLED", 1),
                            ("DISABLED", 2),
                            ("DESTROYED", 3),
                        ]
                    ),
                ),
                (
                    "output_prefix_type",
                    models.PositiveIntegerField(
                        choices=[
                            ("UNKNOWN_PREFIX", 0),
                            ("TINK", 1),
                            ("LEGACY", 2),
                            ("RAW", 3),
                            ("CRUNCHY", 4),
                        ]
                    ),
                ),
                ("output_prefix", models.BinaryField()),
                (
                    "keyset",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tink_fields.keyset",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="key",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("keyset", "is_primary"),
                name="one_primary_per_keyset",
            ),
        ),
    ]
